# Enterprise Retail Sales & Customer Analytics Platform

## Data Cleaning

### Objective
The objective of this notebook is to clean and validate the retail dataset before performing exploratory data analysis and building dashboards.

**Tools Used**
- Python
- Pandas
- NumPy

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [5]:
# Load Orders sheet
df = pd.read_csv(
    "Dataset.csv",)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,03-01-2023,07-01-2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,04-01-2023,08-01-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,04-01-2023,08-01-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,04-01-2023,08-01-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,05-01-2023,12-01-2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [6]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 10194
Columns : 21

In [7]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [9]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})
missing

              Missing Values  Percentage
Row ID                     0         0.0
Order ID                   0         0.0
Order Date                 0         0.0
Ship Date                  0         0.0
Ship Mode                  0         0.0
...                      ...         ...
Product Name               0         0.0
Sales                      0         0.0
Quantity                   0         0.0
Discount                   0         0.0
Profit                     0         0.0

[21 rows x 2 columns]

In [10]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [ ]:
df = df.drop_duplicates()
print(df.shape)

(10194, 21)

In [12]:
df.dtypes

Row ID            int64
Order ID         object
Order Date       object
Ship Date        object
Ship Mode        object
                 ...
Product Name     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
Length: 21, dtype: object

In [13]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [14]:
df[["Order Date","Ship Date"]].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [15]:
print(df["Order Date"].isna().sum())
print(df["Ship Date"].isna().sum())

0
0

In [16]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002942720,2025-05-03 10:52:45.626839296,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [17]:
df.describe(include="object")

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,5111,4,804,800,3,2,542,59,654,4,1862,3,17,1849
top,US-2026-100111,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,10035,West,FUR-FU-10004270,Office Supplies,Binders,Staples
freq,14,6120,41,41,5281,9994,915,2001,263,3253,20,6128,1548,50

In [20]:
for col in ["Category","Sub-Category","Segment","Region","Ship Mode"]:
    print("="*50)
    print(col)
    print(df[col].unique())

==================================================
Category
['Office Supplies' 'Furniture' 'Technology']
==================================================
Sub-Category
['Paper' 'Binders' 'Labels' 'Storage' 'Art' 'Chairs' 'Fasteners' 'Phones'
 'Furnishings' 'Accessories' 'Bookcases' 'Envelopes' 'Appliances' 'Tables'
 'Supplies' 'Machines' 'Copiers']
==================================================
Segment
['Consumer' 'Home Office' 'Corporate']
==================================================
Region
['Central' 'East' 'South' 'West']
==================================================
Ship Mode
['Standard Class' 'First Class' 'Second Class' 'Same Day']

In [21]:
loss_orders = df[df["Profit"]<0]
print("Loss Orders :",len(loss_orders))

Loss Orders : 1901

In [22]:
df["Discount"].value_counts().sort_index()

Discount
0.00    4925
0.10      96
0.15      52
0.20    3706
0.30     230
0.32      27
0.40     207
0.45      11
0.50      66
0.60     149
0.70     424
0.80     301
Name: count, dtype: int64

In [23]:
df["Shipping Days"] = (
    df["Ship Date"]-df["Order Date"]
).dt.days

In [24]:
df[["Order Date","Ship Date","Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2023-01-03 2023-01-07              4
1 2023-01-04 2023-01-08              4
2 2023-01-04 2023-01-08              4
3 2023-01-04 2023-01-08              4
4 2023-01-05 2023-01-12              7

In [25]:
print(df.shape)

(10194, 22)

In [26]:
df.to_csv(
    "clean_superstore.csv",
    index=False
)

print("Clean Dataset Exported Successfully")

Clean Dataset Exported Successfully